# Generated by Django 6.0.4 on 2026-04-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cita',
            name='metodo_pago',
            field=models.CharField(default='Efectivo', max_length=100),
        ),
        migrations.AddField(
            model_name='cita',
            name='monto_pagado_adelantado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cita',
            name='monto_pagado_dia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
